name: yamobile.leadtracker::lang.lead.breadcrumb-create
form: $/yamobile/leadtracker/models/lead/fields.yaml
modelClass: Yamobile\LeadTracker\Models\Lead
defaultRedirect: yamobile/leadtracker/lead
create:
  redirect: "yamobile/leadtracker/leads/update/:id"
  redirectClose: yamobile/leadtracker/lead
update:
  redirect: yamobile/leadtracker/lead
  redirectClose: yamobile/leadtracker/lead
